### ISSUE TITLE
Ломается Escape

### ISSUE THREAD

**Issue by npofopr** [shvetsgroup/atom-glvrd#1]
После установки ломается закрытие окошек по `Esc`, любых. Например, поиск не закрывается и т.п.
Windows 10.

**Comment by neochief** [comment]
Спасибо за баг-репорт. Баг исправлен в версии 0.3.0, которую я только что залил.

Буду рад услышать от вас любые замечания и пожелания, т.к. вы похоже второй пользователь плагина)
